site_name: "Networking with the micro:bit"


# see https://github.com/Microsoft/pxt-mkdocs-sample
libs: jquery
extra_javascript: [embed.js]

theme: readthedocs

nav:
- 'Home': 'README.md'
- 'Connecting micro:bits with wires': wiredcommunication/wiredcommunication.md
- 'Broadcast communication': broadcast/broadcast.md
- 'Group communication': groupcommunication/groupcommunication.md
- 'Game 1: Shakey Donkey': shakeydonkey/shakeydonkey.md
 
 
 
